const fs = require('fs');
const https = require('https');
const ffmpeg = require('fluent-ffmpeg');

// Function to download the background music
async function downloadAsset(url, dest) {
    return new Promise((resolve, reject) => {
        const file = fs.createWriteStream(dest);
        https.get(url, (res) => {
            if (res.statusCode !== 200) return reject(new Error(`Download Failed: ${res.statusCode}`));
            res.pipe(file);
            file.on('finish', () => { file.close(); resolve(); });
        }).on('error', reject);
    });
}

async function startMixing() {
    try {
        console.log("📥 Downloading Background Music...");
        const bgmUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3";
        await downloadAsset(bgmUrl, 'bgm.mp3');

        console.log("🎵 Mixing Audio Tracks...");
        return new Promise((resolve, reject) => {
            ffmpeg()
                .input('voiceover.mp3') // Generated by your index.js
                .input('bgm.mp3')
                .complexFilter([
                    {
                        filter: 'volume',
                        options: { volume: '0.15' }, // Lower BGM so voice is clear
                        inputs: '1:a',
                        outputs: 'bgm_quiet'
                    },
                    {
                        filter: 'amix',
                        options: { inputs: 2, duration: 'first' },
                        inputs: ['0:a', 'bgm_quiet']
                    }
                ])
                .on('start', (cmd) => console.log('🚀 FFmpeg started mixing...'))
                .on('error', (err) => {
                    console.error('❌ Mixing Error:', err.message);
                    reject(err);
                })
                .on('end', () => {
                    console.log('✅ Success: mixed_audio.mp3 created.');
                    resolve();
                })
                .save('mixed_audio.mp3');
        });
    } catch (error) {
        console.error("🚨 Mixer Failed:", error);
        process.exit(1);
    }
}

startMixing();
                    
