const fs = require('fs');
const gTTS = require('gtts');

async function generateContent() {
    // 1. GET THE NICHE FROM DASHBOARD OR DEFAULT
    // If the dashboard sent a niche, we use it. Otherwise, we default to your main niche.
    const activeNiche = process.env.INPUT_NICHE || "How to Go Viral on YouTube";

    console.log(`🎯 Active Niche: ${activeNiche}`);

    // 2. CREATE DYNAMIC SCRIPT BASED ON NICHE
    const scriptText = `If you want to master ${activeNiche}, you need to understand one thing. Consistency and value are the only ways to win in the current algorithm.`;
    
    const metadata = {
        title: `${activeNiche}: The Ultimate Secret`,
        description: `Everything you need to know about ${activeNiche}. Generated by AutoTube. #YouTube #Automation #${activeNiche.replace(/\s+/g, '')}`,
        tags: [activeNiche, "Viral", "YouTube Strategy", "AutoTube"],
        duration: 10
    };
    
    // Save metadata for the video engine and uploader to read
    fs.writeFileSync('metadata.json', JSON.stringify(metadata, null, 2));
    console.log("📝 Metadata and Script synced.");

    // 3. GENERATE THE AUDIO
    const gtts = new gTTS(scriptText, 'en');
    return new Promise((resolve, reject) => {
        gtts.save('voiceover.mp3', (err) => {
            if (err) reject(err);
            else {
                console.log("🎙️ Voiceover generated for: " + activeNiche);
                resolve();
            }
        });
    });
}

generateContent().catch(console.error);
